name: Validate pull request

on:
  pull_request_target:
    types:
      - opened

permissions:
  contents: read
  statuses: write
  pull-requests: write

jobs:
  testing:
    uses: AdobeDocs/commerce-php/.github/workflows/validate-pr_job.yml@main
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
